dist: trusty

language: node_js
node_js:
  - '12'

script:
  - npm run test
  - npm run e2e

stages:
  - test
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: lint
      name: "Linting"
      script: npm run lint
    - stage: build
      name: "Build production"
      script: npm run build
    - stage: deploy
      name: "Deploy GH pages"
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: false
        local_dir: dist
        target_branch: gh-pages
        on:
          branch: master