dist: trusty

language: node_js
node_js:
  - '12'

stages:
  - test
  - build
  - lint
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      addons:
        chrome: stable
      name: "Unit Tests"
      script: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
    - name: "End-2-End Tests"
      script: 
        - echo CHROME VERSION $(google-chrome --version)
        - xvfb-run npm run e2e
    - stage: lint
      name: "Linting"
      script: npm run lint
    - stage: build
      name: "Production"
      script: npm run build
    - stage: deploy
      name: "GitHub Pages"
      script: npm run build -- --base-href \"/papyrus/\"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: false
        local_dir: dist
        target_branch: gh-pages
        on:
          branch: master